import { Data as hololive_about } from '../data/hololive/about';
import { Data as hololive_channels } from '../data/hololive/channels';
import { Data as hololive_channels_subscriptions } from '../data/hololive/channels/subscriptions';
import { Data as hololive_channels_custom12 } from '../data/hololive/channels/custom-12';
import { Data as hololive_community } from '../data/hololive/community';
import { Data as hololive_playlists } from '../data/hololive/playlists';
import { Data as hololive_podcasts } from '../data/hololive/podcasts';
import { Data as hololive_shorts } from '../data/hololive/shorts';
import { Data as hololive_streams } from '../data/hololive/streams';
import { Data as hololive_videos } from '../data/hololive/videos';
import { Data as haachamachama_about } from '../data/AkaiHaato/about';
import { Data as haachamachama_playlists } from '../data/AkaiHaato/playlists';
import { Data as haachamachama__video } from '../data/AkaiHaato/_videos/KpCH4mbj_pk';
import { Data as suisei_about } from '../data/HoshimachiSuisei/about';
import { Data as suisei_releases } from '../data/HoshimachiSuisei/releases';
import { Data as suiseiTopic } from '../data/HoshimachiSuisei-Topic/about';
import { Data as manae_nme_about } from '../data/manae_nme/about';
import { Data as manae_nme_channels } from '../data/manae_nme/channels';
import { Data as Anko_Kisaki_channels } from '../data/Anko_Kisaki/channels';
import { Data as AkaiHaato_featured } from '../data/AkaiHaato/featured';
import { Data as fuurayuri_featured } from '../data/fuurayuri/featured';
import { Data as fuurayuri_about } from '../data/fuurayuri/about';
import { Data as AsahinaAkane_community } from '../data/AsahinaAkane/community';
import { Data as AmrzsMonstar_community } from '../data/AmrzsMonstar/community';
import { Data as ManoAloe_community } from '../data/ManoAloe/community';
import { Data as ManoAloe_about } from '../data/ManoAloe/about';
import { Data as ManoAloe_playlists } from '../data/ManoAloe/playlists';
import { Data as KMNZ_channels } from '../data/KMNZ/channels';
import { Data as UruhaRushia_featured } from '../data/UruhaRushia/featured';
import { Data as GundoMirei_membership } from '../data/GundoMirei/membership';
import { Data as c0 } from '../data/channels/UCRbsmnDTHD9-4pEIuG7zYRw/about';
import { Data as c1 } from '../data/channels/UCc2MFmkMC_tHND7TDHrRDkg/about';
import { Data as c2 } from '../data/channels/UC5CwaMl1eIgY8h02uZw7u8A/about';
import { Data as c3 } from '../data/channels/UC5CwaMl1eIgY8h02uZw7u8A/about-withAuth';
import { Data as c4 } from '../data/channels/UCrzT1p8gn0hQTBeMA6e2YiA/about';
import { Data as c5 } from '../data/channels/UCrzT1p8gn0hQTBeMA6e2YiA/about-withAuth';
import { Data as c6 } from '../data/channels/UCwuS0uY-Z2Gr_5OV2oFybFA/videos';
import { Data as c7 } from '../data/channels/UCKQi12nOGZsJ5nOuCTHErmA/featured';
import { Channel } from '../export/url/channel';

type ChannelPage = Channel['ytInitialData'];

<hololive_about>{} satisfies ChannelPage;
<hololive_channels>{} satisfies ChannelPage;
<hololive_channels_subscriptions>{} satisfies ChannelPage;
<hololive_channels_custom12>{} satisfies ChannelPage;
<hololive_community>{} satisfies ChannelPage;
<hololive_playlists>{} satisfies ChannelPage;
<hololive_podcasts>{} satisfies ChannelPage;
<hololive_shorts>{} satisfies ChannelPage;
<hololive_streams>{} satisfies ChannelPage;
<hololive_videos>{} satisfies ChannelPage;
<haachamachama_about>{} satisfies ChannelPage;
<haachamachama_playlists>{} satisfies ChannelPage;
<haachamachama__video>{} satisfies ChannelPage;
<suisei_about>{} satisfies ChannelPage;
<suisei_releases>{} satisfies ChannelPage;
<suiseiTopic>{} satisfies ChannelPage;
<manae_nme_about>{} satisfies ChannelPage;
<manae_nme_channels>{} satisfies ChannelPage;
<Anko_Kisaki_channels>{} satisfies ChannelPage;
<AkaiHaato_featured>{} satisfies ChannelPage;
<fuurayuri_featured>{} satisfies ChannelPage;
<fuurayuri_about>{} satisfies ChannelPage;
<AsahinaAkane_community>{} satisfies ChannelPage;
<AmrzsMonstar_community>{} satisfies ChannelPage;
<ManoAloe_community>{} satisfies ChannelPage;
<ManoAloe_about>{} satisfies ChannelPage;
<ManoAloe_playlists>{} satisfies ChannelPage;
<KMNZ_channels>{} satisfies ChannelPage;
<UruhaRushia_featured>{} satisfies ChannelPage;
<GundoMirei_membership>{} satisfies ChannelPage;
<c0>{} satisfies ChannelPage;
<c1>{} satisfies ChannelPage;
<c2>{} satisfies ChannelPage;
<c3>{} satisfies ChannelPage;
<c4>{} satisfies ChannelPage;
<c5>{} satisfies ChannelPage;
<c6>{} satisfies ChannelPage;
<c7>{} satisfies ChannelPage;
