import { Data as hololive_about } from '../data/hololive/about';
import { Data as hololive_channels } from '../data/hololive/channels';
import { Data as hololive_channels_subscriptions } from '../data/hololive/channels/subscriptions';
import { Data as hololive_channels_custom12 } from '../data/hololive/channels/custom-12';
import { Data as hololive_community } from '../data/hololive/community';
import { Data as hololive_playlists } from '../data/hololive/playlists';
import { Data as hololive_podcasts } from '../data/hololive/podcasts';
import { Data as hololive_shorts } from '../data/hololive/shorts';
import { Data as hololive_streams } from '../data/hololive/streams';
import { Data as hololive_videos } from '../data/hololive/videos';
import { Data as haachamachama_about } from '../data/AkaiHaato/about';
import { Data as haachamachama_playlists } from '../data/AkaiHaato/playlists';
import { Data as haachamachama__video } from '../data/AkaiHaato/_videos/KpCH4mbj_pk';
import { Data as suisei_about } from '../data/HoshimachiSuisei/about';
import { Data as suisei_releases } from '../data/HoshimachiSuisei/releases';
import { Data as suiseiTopic } from '../data/HoshimachiSuisei-Topic/about';
import { Data as manae_nme_about } from '../data/manae_nme/about';
import { Data as manae_nme_channels } from '../data/manae_nme/channels';
import { Data as Anko_Kisaki_channels } from '../data/Anko_Kisaki/channels';
import { Data as AkaiHaato_featured } from '../data/AkaiHaato/featured';
import { Data as fuurayuri_featured } from '../data/fuurayuri/featured';
import { Data as fuurayuri_about } from '../data/fuurayuri/about';
import { Data as AsahinaAkane_community } from '../data/AsahinaAkane/community';
import { Data as AmrzsMonstar_community } from '../data/AmrzsMonstar/community';
import { Data as ManoAloe_community } from '../data/ManoAloe/community';
import { Data as ManoAloe_about } from '../data/ManoAloe/about';
import { Data as ManoAloe_playlists } from '../data/ManoAloe/playlists';
import { Data as KMNZ_channels } from '../data/KMNZ/channels';
import { Data as UruhaRushia_featured } from '../data/UruhaRushia/featured';
import { Data as GundoMirei_membership } from '../data/GundoMirei/membership';

import { Channel } from '../export/channel';



<hololive_about>{} satisfies Channel;
<hololive_channels>{} satisfies Channel;
<hololive_channels_subscriptions>{} satisfies Channel;
<hololive_channels_custom12>{} satisfies Channel;
<hololive_community>{} satisfies Channel;
<hololive_playlists>{} satisfies Channel;
<hololive_podcasts>{} satisfies Channel;
<hololive_shorts>{} satisfies Channel;
<hololive_streams>{} satisfies Channel;
<hololive_videos>{} satisfies Channel;
<haachamachama_about>{} satisfies Channel;
<haachamachama_playlists>{} satisfies Channel;
<haachamachama__video>{} satisfies Channel;
<suisei_about>{} satisfies Channel;
<suisei_releases>{} satisfies Channel;
<suiseiTopic>{} satisfies Channel;
<manae_nme_about>{} satisfies Channel;
<manae_nme_channels>{} satisfies Channel;
<Anko_Kisaki_channels>{} satisfies Channel;
<AkaiHaato_featured>{} satisfies Channel;
<fuurayuri_featured>{} satisfies Channel;
<fuurayuri_about>{} satisfies Channel;
<AsahinaAkane_community>{} satisfies Channel;
<AmrzsMonstar_community>{} satisfies Channel;
<ManoAloe_community>{} satisfies Channel;
<ManoAloe_about>{} satisfies Channel;
<ManoAloe_playlists>{} satisfies Channel;
<KMNZ_channels>{} satisfies Channel;
<UruhaRushia_featured>{} satisfies Channel;
<GundoMirei_membership>{} satisfies Channel;
